category_boxes_with_subcategories:
  default: ""
  type: list
  list_type: category
  description: "Select which category boxes with subcategories you would like to hide."
category_hamburger:
  default: "example-slug-category"
  type: list
  description: "Enter the category slugs for each category you would like to hide in the hamburger menu."
category_boxes_wih_featured_topics:
  default: "example-slug-category"
  type: list
  description: "Enter the category slugs for each category box you would like to hide."
category_list:
  default: ""
  type: list
  list_type: category
  description: "Select which categories from the category list to hide"
hide_all_subcategories_in_hamburger:
  default: false
  type: bool
  description: "Select to hide all subcategories from appearing in the hamburger menu."
hide_all_subcategories_in_category_list:
  default: false
  type: bool
  description: "Select to hide all subcategories from appearing in the category list."
category_breadcrumb:
  default: "Sample Name"
  type: list
  description: "Enter the name of the category which should be hidden in the category breadcrumb selector."
