category_boxes_with_subcategories:
  default: ''
  type: list
  list_type: category
  description: 'Select which category boxes with subcategories you would like to hide.'
category_hamburger:
  default: 'example-slug-category'
  type: list
  description: 'Enter the category slugs for each category you would like to hide in the hamburger menu.'
category_boxes_wih_featured_topics:
  default: 'example-slug-category'
  type: list
  description: 'Enter the category slugs for each category you would like to hide in the hamburger menu.'
category_list:
  default: ''
  type: list
  list_type: category
  description: 'Select which categories from the category list to hide'
